// 端口聚合出口: outer/adapter 层从这里取 core 定义的端口契约。
export * from './HttpPort'
export * from './StoragePort'
export * from './DomParserPort'
export * from './YamlPort'
export * from './PinyinPort'
export * from './MarkdownPort'
export * from './SearchEnginePort'
export * from './FileSystemPort'
export * from './VersionControlPort'
export * from './WordSegmenterPort'
export * from './SearchIndexPort'
export * from './CachePort'
export * from './CommitHistoryPort'
export * from './CategoryProviderPort'
export * from './DocClusterPort'
