name: 回源触发

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron:  '0 0/6 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 安装依赖
      run: |
        npm install
    - name: 回源触发
      run: |
        npm run back-origin
    - name: 回源快照存档
      uses: actions/upload-artifact@v2
      with:
        name: snapshot
        path: |
          back_origin_snapshot
    - name: note.ismy.wang快照
      uses: actions/upload-artifact@v2
      with:
        name: note.ismy.wang
        path: |
          back_origin_snapshot/note.ismy.wang0.png
    - name: noteg.ismy.wang快照
      uses: actions/upload-artifact@v2
      with:
        name: noteg.ismy.wang
        path: |
          back_origin_snapshot/noteg.ismy.wang0.png
    - name: notev.ismy.wang快照
      uses: actions/upload-artifact@v2
      with:
        name: notev.ismy.wang
        path: |
          back_origin_snapshot/notev.ismy.wang0.png
    