name: '增量更新搜索索引'

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8]

    steps:
    - uses: actions/checkout@v1
    - name: 设置python环境
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      env:
        # 注意在 Settings->Secrets 配置
        ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
        ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
    - name: python依赖安装
      run: |
        pip install algoliasearch==2.5.0 beautifulsoup4==4.9.3 markdown==3.3.4
    - name: 执行索引增量更新
      run: |
        python ./scripts/update_index.py ${{ secrets.ALGOLIA_APP_ID }} ${{ secrets.ALGOLIA_API_KEY }} ${{ secrets.ALGOLIA_INDEX_NAME }} increment
      env:
        CI: true
